### ISSUE TITLE
项目引用了com.alibaba:fastjson@1.2.68等14个开源组件，存在1个严重漏洞，建议升级

### ISSUE THREAD

**Issue by Abbylii** [Eiriksgata/rulateday-api#3]
大佬，看你这个项目调用了com.alibaba:fastjson@1.2.68等14个开源组件，存在1个安全漏洞，建议你升级下。
```
漏洞标题：Fastjson <=1.2.68 远程代码执行漏洞
漏洞编号：
漏洞描述：
Fastjson 是Java语言实现的快速JSON解析和生成器，在<=1.2.68的版本中攻击者可通过精心构造的JSON请求，远程执行恶意代码。
漏洞原因：
Fastjson采用黑白名单的方法来防御反序列化漏洞，导致当黑客不断发掘新的反序列化Gadgets类时，发现在autoType关闭的情况下仍然可能可以绕过黑白名单防御机制，造成远程命令执行漏洞。
国家漏洞库信息：https://www.cnvd.org.cn/flaw/show/CNVD-2020-30827
漏洞级别：严重
影响范围：(-∞, 1.2.69)
最小修复版本：sec10
引入路径：
indi.eiriksgata:rulateday-api:0.0.1-SNAPSHOT:->indi.eiriksgata:rulateday-api@0.0.1-SNAPSHOT->com.alibaba:fastjson@1.2.68
```
还有其它几个漏洞，信息有点多我就不贴了，你自己看下完整报告：https://www.mfsec.cn/jr?p=aa8045

**Comment by Eiriksgata** [comment]
你这是机器人吗，发现的这么快，虽然我项目也没开Security 感觉应该没有人关注才对

**Comment by Abbylii** [comment]
嘿嘿，是真人哦

**Comment by Abbylii** [comment]
Hi,
       
      大佬您好！我是Abby，看到了您issue的回复，目前我们在做漏洞扫描的安全工具，了解更多可以加我的微信哦👇，
我们还聚集了一个技术交流社区，大家一起可以多交流交流(*^▽^*)~


在2022年1月21日 ***@***.***> 写道：

你这是机器人吗，发现的这么快，虽然我项目也没开Security 感觉应该没有人关注才对

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Eiriksgata** [comment]
> Hi, 大佬您好！我是Abby，看到了您issue的回复，目前我们在做漏洞扫描的安全工具，了解更多可以加我的微信哦👇， 我们还聚集了一个技术交流社区，大家一起可以多交流交流(*^▽^*)~ 在2022年1月21日 ***@***.***> 写道： 你这是机器人吗，发现的这么快，虽然我项目也没开Security 感觉应该没有人关注才对 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

谢谢，不用了。这个项目之前没有开启 Github Dependabot alerts ，实际上你们的扫描也是主要面对 dependency  。code security 有更为成熟的 例如： GitGuardian 。
